version: "3.9"
services:
    app:
        build: ./infra/app
        volumes:
            - ./project:/work
            - /project/node_modules
        restart: always
        working_dir: /work
        tty: true
        ports:
            - ${APP_PORT:-5173}:5173
    web:
        image: nginx:1.20-alpine
        ports:
            - 8081:80
        volumes:
            - ./project:/work
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /work
        depends_on:
            - app
